movieapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'movieapp'
urlpatterns = [
    path('', views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_data,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

moviestock/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from moviestock import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL,
                              document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class cinema_table(models.Model):
    name = models.CharField(max_length=500)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='pics')

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from movieapp.form import cinemaform
from movieapp.models import cinema_table


# Create your views here.
def index(request):
    movie= cinema_table.objects.all()
    contex = { 'movie_list':movie }
    return render(request,"index.html",contex)

def detail(request, movie_id):
    shoot = cinema_table.objects.get(id=movie_id)
    return render(request,"detail.html",{'script':shoot})

def add_data(request):
    if request.method =="POST":
        name = request.POST.get('name',)
        year = request.POST.get('year',)
        desc = request.POST.get('desc',)
        img = request.FILES['img']
        movie=cinema_table(name=name,year=year,desc=desc,img=img)
        movie.save();
    return render(request,"add.html")

def update(request,id):
    story = cinema_table.objects.get(id=id)
    form = cinemaform(request.POST or None,request.FILES,instance=story)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'movie':story,'form':form})

def delete(request,id):
    if request.method == "POST":
        cancel = cinema_table.objects.get(id=id)
        cancel.delete();
        return redirect('/')
    return render(request,"delete.html")

templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Movies</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
  <input type="text" name="name" placeholder="Enter movie name">
  <input type="texteria" name="desc" placeholder="Enter the details">
  <input type="text" name="year" placeholder="Enter the year">
  <input type="file" name="img">
  <input type="submit">
</form>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this ?
    <input type="submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<!-- <img src=""><br>
<br>
{{script.desc}}<br>
<a class="btn btn-warning" href="{% url 'movieapp:update' script.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' script.id %}">delete</a>  -->

<br>
<div class="container">
<div class="row">
 <div class="col-md-12">   
<div class="card mb-3" >
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="{{script.img.url}}" class="card-img" alt="..." >
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title" style="text-align: center; font-family: 'Times New Roman', Times, serif; font-size: 50px; text-transform: uppercase;">{{script.name}}</h2>
          <hr style="border: 2;"
          <p class="card-text">{{script.desc}}</p>
          <p class="card-text" style="padding-top: 15%; text-align: right;"><a class="btn btn-warning" href="{% url 'movieapp:update' script.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' script.id %}">delete</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
{% endblock %}

templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}
<br>
<div class="container">
 <div class="row"> 
    {% for i in movie_list %}  
<div class="col-md-3">
 
<div class="card" style="width: 18rem;">
    <img src="{{i.img.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{i.name}}({{i.year}})</h5>
      <!-- <p class="card-text">{{i.desc}}</p> -->
      <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-warning">view</a>
    </div>
  </div>
  <br>
</div>

<div class="col-md-1"></div>
{% endfor %}

</div>

</div>



{% endblock %}